### ISSUE TITLE
Can't remove number in FireFox

### ISSUE THREAD

**Issue by edmenendez** [rajaramtt/jquery-input-mask-phone-number#1]
Using FF go to: https://jsfiddle.net/1kbat1nb/
Enter a complete number. Then try to delete numbers. 

result: it doesn't let you delete the first 6 numbers.
expected outcome: you should be able to edit the numbers.

http://supportdetails.net/GWJHDMCV

**Comment by edmenendez** [comment]
And I think this would fix it:

`                if (curchr == 3 && e.which != 8 && e.which != 0) {
                    $(this).val('(' + curval + ')' + " ");
                } else if (curchr == 9 && e.which != 8 && e.which != 0) {
                    $(this).val(curval + "-");
                }
`

Added a test for del/backspace. Timing must be different on FF.

**Comment by rajaramtt** [comment]
The issue has been fixed, Please verify!.
