### ISSUE TITLE
Doesn't work in Chrome for Android

### ISSUE THREAD

**Issue by JohnBakery** [rajaramtt/jquery-input-mask-phone-number#2]
It doesn't work in Chrome for Android. it doesn't apply masking at all.

**Comment by rajaramtt** [comment]
Thanks for the posting issue!. Identified the root cause Need to fix

**Comment by KelseyDH** [comment]
Weird, what version?  I tested this on Chrome for Android on browser stack and it was working?

**Comment by rajaramtt** [comment]
Please verify the latest version 


http://jsfiddle.net/rajaramtt/7s3eLokc/22/
