### ISSUE TITLE
Keying back and deleting at "-" breaks mask

### ISSUE THREAD

**Issue by KelseyDH** [rajaramtt/jquery-input-mask-phone-number#3]
Trying this library out for robustness.  After entering in a number, if someone hits their arrow key back to a "-" and hits delete this library deletes the "-".

Instead hitting delete should gracefully shift the numbers back without affecting the dashes (minus removing them if there are not enough numbers.

![Screen Shot 2019-11-26 at 2 31 55 PM](https://user-images.githubusercontent.com/6710303/69678226-cd41d980-1059-11ea-9022-76dc31274d82.png)

**Comment by rajaramtt** [comment]
Please verify latest version 

http://jsfiddle.net/rajaramtt/7s3eLokc/22/
