### ISSUE TITLE
Newest build has logic error

### ISSUE THREAD

**Issue by JoshKasap** [rajaramtt/jquery-input-mask-phone-number#5]
The current program has an issue where validation checks are being done after input. So i can type characters as well as numbers and go over the normal phone number limit. 

However, using this version 1.0.11 posted at [npmjs.com](https://www.npmjs.com/package/jquery-input-mask-phone-number) works flawlessly. 

I can see comparing the 2 files that the difference is on line 33 and 48

33`$(this).on('keyup', function (e) {` most recent on github
33`$(this).on('keydown touchend', function (e) {` version 1.0.11 posted at npmjs.com
48`$(this).on('keyup', function (e) {` most recent on github
48`$(this).on('keydown touchend', function (e) {` version 1.0.11 posted at npmjs.com

The only downside i noticed when using 1.0.11 on npmjs is that ctrl + v to paste numbers won't work however, right click and paste still does. 

Ideally you might wan't to handle both issues somehow.

**Comment by rajaramtt** [comment]
ctrl + v The issue has been fixed, Please verify 

http://jsfiddle.net/rajaramtt/7s3eLokc/22/
