### ISSUE TITLE
Entering number with 1 (country code) loses final number

### ISSUE THREAD

**Issue by Devpaq** [rajaramtt/jquery-input-mask-phone-number#6]
Many people enter their phone number including the initial 1 (ex: 1-212-123-4567)
If someone does that it will only take the first 10 digits and drop the last digit. 
Is there any way to set it to remove the initial 1 if they start the number with 1?

**Comment by rajaramtt** [comment]
@Devpaq  We are currently supporting  (xxx) xxx-xxxx or xxx-xxx-xxxx formatls only . 
for country codes, please use prepend text for the input box.
