### ISSUE TITLE
Tab out from input not working

### ISSUE THREAD

**Issue by mayureshs** [rajaramtt/jquery-input-mask-phone-number#8]
After initiating this call, the tab out functionality is no longer working
		$('#txtPhone').usPhoneFormat({
			format: '(xxx) xxx-xxxx'
		});

**Comment by rajaramtt** [comment]
@mayureshs  Issue alredy addressed avilable latest version  https://www.npmjs.com/package/jquery-input-mask-phone-number/v/1.0.14, Please verify.

Working Fiddle Example: 
http://jsfiddle.net/rajaramtt/7s3eLokc/23/
